<?php require 'header.php'?>
    <section>
        <div class="infodiv">
            <div class="divorg">    
                <div class="adequada">
                <div class="img-zoom-container">
                <img id="myimage" src="img/Exemplo.jpg">
                 <div id="myresult" class="img-zoom-result"></div>
                </div>
    
                <div class="secondorg">
                    <div>
                    <img src="img/Exemplo.jpg" alt="" class="imgsecond">
                    </div>
                    <div>
                    <img src="img/exemplocostas.jpg" alt="" class="imgsecond">
                    </div>
                </div>
            </div>

            <div id="descricao">
                <h1 id="titulo" aria-label="Titulo do Livro">Geometria Analítica um tratamento vetorial </h1>
                <p id="autor" aria-label="nome dos autores">Ivan de Camargo & Paulo Boulos</p>
                <h2 id="star">
                    <img src="img/estrela-vazia.png" alt="estrela 1" class="star">
                    <img src="img/estrela-vazia.png" alt="estrela 2" class="star">
                    <img src="img/estrela-vazia.png" alt="estrela 3" class="star">
                    <img src="img/estrela-vazia.png" alt="estrela 4" class="star">
                    <img src="img/estrela-vazia.png" alt="estrela 5" class="star">
                </h2>



                <div>
                <p class="categ"> <strong><i>Científico</i></strong></p>
                <p class="categ"> <strong><i>Acadêmico</i></strong></p>
                <p class="categ"> <strong><i>Didático/Pedagógico</i></strong></p>
            </div>
                <h1>Descrição</h1>
                <p id="p-descricao">Bom estado, leve desgaste da capa, páginas bem amareladas com pontos de oxidação nas
                    laterais. Conteúdo sem grifos ou rasuras. <br>
                    <a href="#titulo-segsection" class="link-livro" aria-label="Link para mais detalhes sobre o livro">Mais detalhes</a>
                </p>
                <p id="disponivel">3 Livros disponíveis para a troca</p>
                <a href="" id="quero-trocar" aria-label="link para fazer a troca do livro">   
                    <p id="troca"><strong><i>Quero Trocar</i></strong></p>
                </a>
            </div>
        </div>
    </section>

    <section id="titulo-segsection" class="titulo-segsection" >
        <div id="seg-section">
            <h1 class="titulo-segsection">Sinopse:</h1>
            <p id="descricao-sinopse">Nova edição de Geometria Analítica - Um Tratamento Vetorial confirma sua posição
                como um clássico das ciências exatas. Ampliado e completamente revisto pelos autores, o livro traz
                centenas de novos exemplos e exercícios, além de ilustrações totalmente refeitas. Possui novo layout que
                proporciona uma leitura mais agradável e facilita a compreensão e a localização de tópicos e exercícios,
                mas a estrutura didática bem-sucedida das edições anteriores foi cuidadosamente mantida. Escrita em
                linguagem clara e objetiva, este livro traz respostas para os exercícios e estratégias de solução, o que
                o torna um guia essencial para o estudo da Geometria. <a
                    href="https://books.google.com/books/about/Geometria_Anal%C3%ADtica.html?id=lmnqAAAACAAJ&source=kp_book_description"
                    target="_blank" class="link-livro" aria-label="link para mais informações sobre o livro no google books">Google Books</a></p> <br>
            <h1 class="titulo-segsection">Detalhes do Produto</h1>
            <div class="detalhes-grid">
                <p><strong>ISBN 10:</strong> 8587918915</p>
                <p><strong>ISBN 13:</strong> 978-8587918918</p>
                <p><strong>Editora:</strong> Pearson Universidades</p>
                <p><strong>Idioma:</strong> Português</p>
                <p><strong>Edição:</strong> - 3ª</p>
                <p><strong>Ano:</strong> 2004</p>
                <p><strong>Páginas:</strong> 560 </p>
                <p><strong>Dimensões:</strong> 27.2 x 20.8 x 2.8 cm</p>
            </div>

        </div>
    </section>

</body>

</html>